name: Build Frontend
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.1'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build